# Generated by Django 4.1.1 on 2022-09-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer', models.CharField(max_length=100)),
                ('tonality', models.CharField(max_length=50)),
                ('piece_name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(default=0)),
                ('master_level', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
