# Generated by Django 4.1.1 on 2022-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('event', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
