# Generated by Django 4.1.1 on 2022-09-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='on_going',
            field=models.BooleanField(default=False),
        ),
    ]
