# Generated by Django 4.1.1 on 2022-09-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_career_on_going'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pieces',
            fields=[
                ('piece_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=200)),
                ('tonality', models.CharField(max_length=100)),
                ('difficulty', models.PositiveIntegerField(max_length=2)),
                ('status', models.PositiveIntegerField(max_length=2)),
                ('link', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('first_page_img', models.CharField(max_length=200)),
                ('note', models.TextField(default='Nothing Special')),
            ],
        ),
    ]
